controllers/countryController.js, readme.md, routes/countries.js
- Get all countries with their unicode flags
- Get a single country with unicode falg
=> feat(countryAPI): add endpoint to get country unicode flags

docs/contribution.md, readme.md
- Adds TOC to readme for easy navigation
- Endpoint Title Naming changed
=> chore(readme.md): update readme with TOC

controllers/countryController.js, helpers/respond.js, readme.md, routes/countries.js
- adds an endpoint to get countries and currencies
=> feat(countryAPI): add endpoint to get countries and currencies

.gitignore, controllers/countryController.js
- fixes case sensitive search for countries
- adds an error handler for countries that are not found
Here's the PR man.
Closes #12
=> fix(countryController/getSinglePosition): fixes get single position controller

app.js, controllers/countryController.js, controllers/dataHub/apiController.js, helpers/finder.js, helpers/respond.js, helpers/utils.js, package-lock.json, package.json, readme.md, routes/countries.js, routes/users.js, services/apiService.js
> This PR:
- adds an endpoint to get all countries and their population data between (1961) - (2018)
- integrates dataHub JSON data endpoints
- adds an endpoint to get a single country and its population data (1961) - (2018)
- adds an endpoint to filter countries and population data by (year, order, orderBy, lt, gt, limit) 
- adds an endpoint to get all cities, related country, and population data
- adds an endpoint to get a city by name, with its population data
- adds an endpoint to filter cities and its population data by (country, order, orderBy, limit)
Closes #9 
Note: both commits are intentional.
Check Readme for Endpoint Documentation.
=> feat(dataHub): adds countries and cities population features

swagger/info/index.js
=> :pencil: (swagger) update url details

model/countriesAndFlag.js
=> :bug: (model) fix svg 404 error issue for certain countries

model/countriesAndCities.js
add Anguilla cities at CountriesAndCities model based on worldpopulationreview.com/countries/cities/anguilla
did I do it correctly? this is my first time to commit other people's project
fix #26
=> :recycle: (countries-and-cities) adding anguilla cities at Model

controllers/countryController.js, routes/countries.js, swagger/openApiDocumentation.js, swagger/paths/random/index.js, test/random.js, test/tests.js
This pull request is in response to issue : https://github.com/MartinsOnuoha/countriesNowAPI/issues/36
for returning a random country object.
=> GET /api/v0.1/countries/random returns a random country object

model/countriesAndCities.js
That country name was changed, now is just Serbia
=> :bug: Country name change

controllers/countryController.js
Sorry if there's a mistake in my commit process 😅
=> :sparkles: now is possible to get cities optionally in filter endpoint

model/countriesAndFlag.js, test/cityInState.js
- heards island uses the same flag as Austria
=> 🐛 (countriesAndFlag.js): change flag for heards island

readme.md
- Fix link to dr5hn/countries-states-cities-database repo 😉
=> Fix link to dr5hn/database repo

controllers/countryController.js, helpers/utils.js, model/countriesAndState.js
=> fix(countriesStateCity.js): fixes naming issue for netherlands

controllers/countryController.js, middlewares/redirectPostToGet.js, routes/countries.js
Redirect all POST routes for the API to GET routes by appending '/q' and a query string built from the POST request
body.
Closes #93
=> :sparkles: (Route: POST /api/v0.1/countries/*) Redirect POST to GET

controllers/countryController.js, middlewares/redirectPostToGet.js
- replaces `for` iterator with `Object.keys` to improve performance.  
- includes return statement to catch blocks
=> :zap: (redirectPostToGet.js) remove iteration over entire prototype chain

model/countriesAndState.js
=> :ambulance: (countriesStateCity.js) add province to states in spain

controllers/countryController.js
- states that ends with "State" should not be formatted
Closes #110
=> :bug: (countryController.js) Fix bug with state names

.circleci/config.yml
=> CHORE(countriesStateCity): add north jackson under ohio

model/countriesAndState.js
=> FIX(countriesAndState): add state suffix

model/countriesAndState.js
=> :bug: (countriesAndState) add Basel-Stadt in Switzerland

controllers/countryController.js, package-lock.json, swagger/paths/filter/index.js, swagger/schemas/returns.js
Adds countries iso selectors (iso2 and iso3) to the filter endpoint
=> :sparkles: (info-filter) extends info filter to support iso

controllers/countryController.js, routes/countries.js
=> :bug: (countryController.js) fix country name query

controllers/countryController.js
allow query for capital field
Closes #157
=> :sparkles: (countryController.js) add query for capital

model/countriesAndUnicodes.js
use same naming for Bahamas country.
Closes #177
=> :bug: (countriesAndUnicodes.js) make "Bahamas" uniform

model/countriesAndCities.js, model/countriesAndState.js, model/countriesAndUnicodes.js
* `Bahamas The` has now been changed to `Bahamas`.
=> FIX: change Bahamas naming

model/countriesAndState.js, model/countriesAndUnicodes.js
=> :art: (countriesAndState.js) remove federal districts from USA states
